import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import FooterComponent from "@/components/footer/Footer-Component";
import GenresSidebarComponent from "@/components/genres-sidebar/GenresSidebarComponent";
import Header from "@/components/header/Header";
import MoviesPage from "@/components/test/TestMovie";
import MenuComponent from "@/components/header/MenuComponent";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type PropType = { children: React.ReactNode };

export default function RootLayout({children}: Readonly<PropType>) {
  return (
      <html lang="en">
      <body className={inter.className} >

        <Header/>
        <div className={'menu-component'}>
        <MenuComponent/>
        <MoviesPage/>
        </div>
        <div className={'main-component'}>
        <GenresSidebarComponent/>
        {children}
         </div>
      <FooterComponent/>


      </body>
      </html>
  );
}